---
- name: Download Tomcat
  get_url: 
    url: "{{ tomcat_download_url }}"
    dest: "/tmp/{{ tomcat_package_name }}"

- name: Install unzip
  apt:
    name: unzip
    state: present

- name: Extract archive
  unarchive:
    src: "/tmp/{{ tomcat_package_name }}"
    dest: /opt
    remote_src: yes

- name: Rename tomcat
  command: "mv /opt/{{ tomcat_package_name }} /opt/tomcat"

- name: Configure Tomcat server
  template:
    src: server.xml 
    dest: /opt/tomcat/conf/
  notify: restart tomcat

- name: Configure Tomcat users
  template: 
    src: tomcat-users.xml 
    dest: /opt/tomcat/conf/
  notify: restart tomcat

- name: Install Tomcat init script
  template: 
    src: tomcat-initscript.sh
    dest: /etc/init.d/tomcat
    mode: 0755

- name: Start Tomcat
  service: 
    name: tomcat 
    state: started 
    enabled: yes
